stages:
  - .pre
  - build
  - deploy

variables:
  APP_VERSION: $CI_PIPELINE_IID

  # Environment substitution

# Branch - Haneesh
env subst Haneesh:
  environment: development-Haneesh
  stage: .pre
  extends: .env subst
  rules:
    - if: $CI_COMMIT_REF_NAME == 'Haneesh'
  artifacts:
    paths:
      - .env
      - firebase.json

# Branch - Lakshmi
env subst Lakshmi:
  environment: development-Lakshmi
  stage: .pre
  extends: .env subst
  rules:
    - if: $CI_COMMIT_REF_NAME == 'Lakshmi'
  artifacts:
    paths:
      - .env
      - firebase.json

# Branch - Mohan
env subst Mohan:
  environment: development-Mohan
  stage: .pre
  extends: .env subst
  rules:
    - if: $CI_COMMIT_REF_NAME == 'Mohan'
  artifacts:
    paths:
      - .env
      - firebase.json

# Branch - Nageswar
env subst Nageswar:
  environment: development-Nageswar
  stage: .pre
  extends: .env subst
  rules:
    - if: $CI_COMMIT_REF_NAME == 'Nageswar'
  artifacts:
    paths:
      - .env
      - firebase.json

# Branch - Development
env subst development:
  environment: development
  stage: .pre
  extends: .env subst
  rules:
    - if: $CI_COMMIT_REF_NAME == 'development'
  artifacts:
    paths:
      - .env
      - firebase.json

# Branch - Production
env subst production:
  environment: production
  stage: .pre
  extends: .env subst
  rules:
    - if: $CI_COMMIT_REF_NAME == 'main'
  artifacts:
    paths:
      - .env
      - firebase.json

# Website Build

build website:
  image: node:16-alpine
  stage: build
  script:
    - yarn install
    - CI=false yarn build
    - echo $APP_VERSION >> build/version.html
  artifacts:
    paths:
      - build

# Deployment

# Haneesh Deployment
deploy to Haneesh:
  stage: deploy
  environment: development-Haneesh
  extends: .deploy
  when: manual
  rules:
    - if: $CI_COMMIT_REF_NAME == 'Haneesh'

# Lakshmi Deployment
deploy to Lakshmi:
  stage: deploy
  environment: development-Lakshmi
  extends: .deploy
  when: manual
  rules:
    - if: $CI_COMMIT_REF_NAME == 'Lakshmi'

# Mohan Deployment
deploy to Mohan:
  stage: deploy
  environment: development-Mohan
  extends: .deploy
  when: manual
  rules:
    - if: $CI_COMMIT_REF_NAME == 'Mohan'

# Nageswar Deployment
deploy to Nageswar:
  stage: deploy
  environment: development-Nageswar
  extends: .deploy
  when: manual
  rules:
    - if: $CI_COMMIT_REF_NAME == 'Nageswar'

# Development Deployment
deploy to development:
  stage: deploy
  environment: development
  extends: .deploy
  when: manual
  rules:
    - if: $CI_COMMIT_REF_NAME == 'development'

# Production Deployment
deploy to production:
  stage: deploy
  environment: production
  extends: .deploy
  when: manual
  rules:
    - if: $CI_COMMIT_REF_NAME == 'main'





.env subst:
  image: centos:7
  script:
    - yum install -y gettext
    - envsubst < gitlab-ci/.env > .env
    - envsubst < gitlab-ci/firebase.json > firebase.json
    - cat .env

.deploy:
  image: node:16-alpine
  before_script:
    - npm i -g firebase-tools
  script:
    - firebase use $PROJECT_NAME --token $FIREBASE_TOKEN
    - firebase deploy --only hosting:$HOSTING_ID -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID @ Hash ${CI_COMMIT_SHA:0:7}" --token $FIREBASE_TOKEN
